apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.keyVault.secretProviderClassName }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "{{ .Values.keyVault.userAssignedIdentityID }}"
    keyvaultName: {{ .Values.keyVault.name }}
    tenantId: {{ .Values.keyVault.tenantId }}
    objects: |
      array:
        - |
          objectName: {{ .Values.keyVault.secretName }}
          objectType: secret
  secretObjects:
    - secretName: {{ .Values.keyVault.k8sSecretName }}
      type: Opaque
      data:
        - objectName: {{ .Values.keyVault.secretName }}
          key: DATABASE_URL
